name: sparkline_console
description: Sparkline for command line applications
version: 0.0.1
homepage: https://github.com/aquilax/sparkline_console
author: aquilax <aquilax@gmail.com>

environment:
  sdk: '>=1.20.1 <2.0.0'

dev_dependencies:
  test: ^0.12.0
