name: sparkline_console
description: Simple sparkline for command line applications. Allows for custom level set.
version: 1.0.3
homepage: https://github.com/aquilax/sparkline_console
author: aquilax <aquilax@gmail.com>

environment:
  sdk: '>=1.20.1 <3.0.0'

dev_dependencies:
  test: ^1.6.3
