name: sparkline_console
description: Simple sparkline for command line applications. Allows for custom level set.
version: 2.0.0
homepage: https://github.com/aquilax/sparkline_console

environment:
  sdk: '>=2.12.0 <3.0.0'

dev_dependencies:
  benchmark_harness: ^2.0.0
  test: ^1.16.8
